revoke all on function public.has_clinic_role(uuid, public.app_role) from public, anon;
revoke all on function public.is_clinic_member(uuid) from public, anon;
revoke all on function public.my_doctor_id(uuid) from public, anon;
revoke all on function public.is_my_doctor_record(uuid) from public, anon;
revoke all on function public.is_my_patient_record(uuid) from public, anon;
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.set_updated_at() from public, anon, authenticated;
grant execute on function public.has_clinic_role(uuid, public.app_role) to authenticated;
grant execute on function public.is_clinic_member(uuid) to authenticated;
grant execute on function public.my_doctor_id(uuid) to authenticated;
grant execute on function public.is_my_doctor_record(uuid) to authenticated;
grant execute on function public.is_my_patient_record(uuid) to authenticated;